### ISSUE TITLE
Firefox addon missing

### ISSUE THREAD

**Issue by leezu** [sourcegraph/sourcegraph-codecov#9]
https://addons.mozilla.org/en-US/firefox/addon/sourcegraph/ linked from https://github.com/sourcegraph/sourcegraph-codecov/blob/master/README.md does not exist

**Comment by leezu** [comment]
https://github.com/sourcegraph/sourcegraph/issues/744#issuecomment-436163831

**Comment by slimsag** [comment]
That timing 😅

**Comment by sqs** [comment]
The Firefox extension is available again. See https://docs.sourcegraph.com/integration/browser_extension.
